"""empty message

Revision ID: 4200ded1cf5b
Revises: 6cd70575035a
Create Date: 2026-05-01 21:22:53.912016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4200ded1cf5b'
down_revision = '6cd70575035a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('calorie_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('macro_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_score', schema=None) as batch_op:
        batch_op.drop_column('macro_score')
        batch_op.drop_column('calorie_score')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
