"""add nutrition score table

Revision ID: b0bba68fa498
Revises: 4200ded1cf5b
Create Date: 2026-05-01 21:56:42.311704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0bba68fa498'
down_revision = '4200ded1cf5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('calorie_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('macro_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_score', schema=None) as batch_op:
        batch_op.drop_column('macro_score')
        batch_op.drop_column('calorie_score')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
