FOODS = [
    {
        "id": "food-1",
        "name": "Fresh Salad",
        "category": "Vegetable",
        "img": "https://picsum.photos/seed/f1/300/200",
        "calories": 85,
        "protein": 2.1,
        "carbs": 8.5,
        "fat": 3.2,
    },
    {
        "id": "food-2",
        "name": "Fruit Bowl",
        "category": "Fruit",
        "img": "https://picsum.photos/seed/f2/300/200",
        "calories": 72,
        "protein": 1.1,
        "carbs": 16.8,
        "fat": 0.4,
    },
    {
        "id": "food-3",
        "name": "Chicken Breast",
        "category": "Protein",
        "img": "https://picsum.photos/seed/f3/300/200",
        "calories": 165,
        "protein": 31,
        "carbs": 0,
        "fat": 3.6,
    },
    {
        "id": "food-4",
        "name": "Yogurt Cup",
        "category": "Snack",
        "img": "https://picsum.photos/seed/f4/300/200",
        "calories": 95,
        "protein": 5.2,
        "carbs": 11.3,
        "fat": 2.7,
    },
    {
        "id": "food-5",
        "name": "Avocado Toast",
        "category": "Breakfast",
        "img": "https://picsum.photos/seed/f5/300/200",
        "calories": 182,
        "protein": 5.4,
        "carbs": 19.2,
        "fat": 8.1,
    },
    {
        "id": "food-6",
        "name": "Healthy Soup",
        "category": "Soup",
        "img": "https://picsum.photos/seed/f6/300/200",
        "calories": 54,
        "protein": 2.8,
        "carbs": 7.2,
        "fat": 1.4,
    },
]

CLIENTS = [
    ("client-1", "Jessie Kim", "jessie@example.com", "Active today"),
    ("client-2", "Lucas Chen", "lucas@example.com", "Needs monitoring"),
    ("client-3", "Emily Park", "emily@example.com", "Good progress"),
]
